### ISSUE TITLE
Pilot fails even though it finishes uploading the Build

### ISSUE THREAD

**Issue by Ybrin** [fastlane/pilot#157] opened 2016-03-01 14:48 UTC
I am currently using pilot together with fastlane in travis-ci and everything works fine, my builds are being uploaded to TestFlight and published to the internal Testers as it should.

But the thing I don't understand is, fastlane finishs with exit code 1 and says "You must provide an answer for this question" without even asking something.

I think this error is pilot related and has nothing to do with fastlane so I am posting this here.

This is the weird output:

```
[12:29:40]: Successfully finished processing the build
[12:29:40]: You can now tweet: 
[12:29:40]: iTunes Connect #iosprocessingtime 15 minutes
[12:29:40]: Distributing new build to testers
[12:29:43]: Variable Dump:
[12:29:43]: {:DEFAULT_PLATFORM=>:ios, :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios beta_ci", :SIGH_PROFILE_TYPE=>"app-store", :LATEST_TESTFLIGHT_BUILD_NUMBER=>3, :BUILD_NUMBER=>"4", :IPA_OUTPUT_PATH=>"/Users/travis/build/KWStudios/Walk-iOS/Pods.ipa", :DSYM_OUTPUT_PATH=>"/Users/travis/build/KWStudios/Walk-iOS/Pods.app.dSYM.zip", :XCODEBUILD_ARCHIVE=>"/Users/travis/Library/Developer/Xcode/Archives/2016-03-01/Pods 2016-03-01 12.06.19.xcarchive"}
[12:29:43]: You must provide an answer for this question.
+------+-------------------------------------+-------------+
|                     fastlane summary                     |
+------+-------------------------------------+-------------+
| Step | Action                              | Time (in s) |
+------+-------------------------------------+-------------+
| 1    | Verifying required fastlane version | 0           |
| 2    | default_platform                    | 0           |
| 3    | cocoapods                           | 110         |
| 4    | match                               | 27          |
| 5    | match                               | 4           |
| 6    | latest_testflight_build_number      | 8           |
| 7    | increment_build_number              | 2           |
| 8    | gym                                 | 413         |
| 9    | pilot                               | 995         |
+------+-------------------------------------+-------------+
[12:29:43]: fastlane finished with errors
-------------------------------------------------------------------------------------------
😨  An error occured. Please enable crash reports using `fastlane enable_crash_reporting`.
👍  This makes resolving issues much easier and helps improve fastlane.
🔒  The reports will be stored securely on getsentry.com.
🙊  More information about privacy: https://github.com/fastlane/fastlane/releases/tag/1.33.3
-------------------------------------------------------------------------------------------
/Users/travis/.rvm/gems/ruby-2.0.0-p643@global/gems/spaceship-0.21.1/lib/spaceship/tunes/tunes_client.rb:219:in `handle_itc_response': [!] You must provide an answer for this question. (Spaceship::TunesClient::ITunesConnectError)
	from /Users/travis/.rvm/gems/ruby-2.0.0-p643@global/gems/spaceship-0.21.1/lib/spaceship/tunes/tunes_client.rb:538:in `update_build_trains!'
	from /Users/travis/.rvm/gems/ruby-2.0.0-p643@global/gems/spaceship-0.21.1/lib/spaceship/tunes/build_train.rb:118:in `update_testing_status!'
	from /Users/travis/.rvm/gems/ruby-2.0.0-p643@global/gems/pilot-1.4.1/lib/pilot/build_manager.rb:124:in `distribute_build'
	from /Users/travis/.rvm/gems/ruby-2.0.0-p643@global/gems/pilot-1.4.1/lib/pilot/build_manager.rb:26:in `upload'
	from /Users/travis/.rvm/gems/ruby-2.0.0-p643@global/gems/fastlane-1.63.1/lib/fastlane/actions/pilot.rb:18:in `run'
	from /Users/travis/.rvm/gems/ruby-2.0.0-p643@global/gems/fastlane-1.63.1/lib/fastlane/runner.rb:143:in `block (2 levels) in execute_action'
	from /Users/travis/.rvm/gems/ruby-2.0.0-p643@global/gems/fastlane-1.63.1/lib/fastlane/actions/actions_helper.rb:35:in `execute_action'
	from /Users/travis/.rvm/gems/ruby-2.0.0-p643@global/gems/fastlane-1.63.1/lib/fastlane/runner.rb:129:in `block in execute_action'
	from /Users/travis/.rvm/gems/ruby-2.0.0-p643@global/gems/fastlane-1.63.1/lib/fastlane/runner.rb:128:in `chdir'
	from /Users/travis/.rvm/gems/ruby-2.0.0-p643@global/gems/fastlane-1.63.1/lib/fastlane/runner.rb:128:in `execute_action'
	from /Users/travis/.rvm/gems/ruby-2.0.0-p643@global/gems/fastlane-1.63.1/lib/fastlane/fast_file.rb:149:in `method_missing'
	from Fastfile:68:in `block (2 levels) in parsing_binding'
	from /Users/travis/.rvm/gems/ruby-2.0.0-p643@global/gems/fastlane-1.63.1/lib/fastlane/lane.rb:36:in `call'
	from /Users/travis/.rvm/gems/ruby-2.0.0-p643@global/gems/fastlane-1.63.1/lib/fastlane/lane.rb:36:in `call'
	from /Users/travis/.rvm/gems/ruby-2.0.0-p643@global/gems/fastlane-1.63.1/lib/fastlane/runner.rb:52:in `block in execute'
	from /Users/travis/.rvm/gems/ruby-2.0.0-p643@global/gems/fastlane-1.63.1/lib/fastlane/runner.rb:46:in `chdir'
	from /Users/travis/.rvm/gems/ruby-2.0.0-p643@global/gems/fastlane-1.63.1/lib/fastlane/runner.rb:46:in `execute'
	from /Users/travis/.rvm/gems/ruby-2.0.0-p643@global/gems/fastlane-1.63.1/lib/fastlane/lane_manager.rb:46:in `cruise_lane'
	from /Users/travis/.rvm/gems/ruby-2.0.0-p643@global/gems/fastlane-1.63.1/lib/fastlane/command_line_handler.rb:30:in `handle'
	from /Users/travis/.rvm/gems/ruby-2.0.0-p643@global/gems/fastlane-1.63.1/bin/fastlane:38:in `block (2 levels) in run'
	from /Users/travis/.rvm/gems/ruby-2.0.0-p643/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Users/travis/.rvm/gems/ruby-2.0.0-p643/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Users/travis/.rvm/gems/ruby-2.0.0-p643/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Users/travis/.rvm/gems/ruby-2.0.0-p643/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Users/travis/.rvm/gems/ruby-2.0.0-p643@global/gems/fastlane_core-0.36.9/lib/fastlane_core/ui/fastlane_runner.rb:23:in `run!'
	from /Users/travis/.rvm/gems/ruby-2.0.0-p643/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Users/travis/.rvm/gems/ruby-2.0.0-p643@global/gems/fastlane-1.63.1/bin/fastlane:156:in `run'
	from /Users/travis/.rvm/gems/ruby-2.0.0-p643@global/gems/fastlane-1.63.1/bin/fastlane:162:in `<top (required)>'
	from /Users/travis/.rvm/gems/ruby-2.0.0-p643/bin/fastlane:23:in `load'
	from /Users/travis/.rvm/gems/ruby-2.0.0-p643/bin/fastlane:23:in `<main>'
	from /Users/travis/.rvm/gems/ruby-2.0.0-p643/bin/ruby_executable_hooks:15:in `eval'
	from /Users/travis/.rvm/gems/ruby-2.0.0-p643/bin/ruby_executable_hooks:15:in `<main>'
The command "fastlane beta_ci" exited with 1.
```

I appreciate any help because being notified for each Commit from travis because of a Failed build is really annoying.

**Comment by sansari** [comment] 2016-03-01 20:12
Just started seeing htis too.

**Comment by alan-andrade** [comment] 2016-03-01 20:13
Same here. We have the exact same error.

**Comment by alan-andrade** [comment] 2016-03-01 20:37
Duplicate of https://github.com/fastlane/pilot/issues/156

**Comment by alan-andrade** [comment] 2016-03-01 23:19
The solution described here worked for us : https://github.com/fastlane/pilot/issues/156#issuecomment-190700461

**Comment by corristo** [comment] 2016-03-02 12:30
Here's what I've got:

```
[13:25:25]: iTunes Transporter successfully finished its job
[13:25:25]: [Transporter]: DBG-X: Returning 0
[13:25:26]: Could not retrieve remote configuration details.
An exception has occurred: Server returned HTTP response code: 403 for URL: https://contentdelivery.itunes.apple.com/transporter/Defaults.properties
[13:25:26]: Could not download/upload from iTunes Connect! It's probably related to your password or your internet connection.
```

**Comment by calebhicks** [comment] 2016-03-02 22:19
I'm getting the same results as @corristo on all uploads.

**Comment by squarefrog** [comment] 2016-03-03 09:17
I've just started getting this after removing `skip_submission: true` from `pilot` options.

**Comment by ciryon** [comment] 2016-03-03 11:13
Same.

**Comment by fastlane-bot-helper** [comment] 2016-03-07 19:55
This issue was migrated to https://github.com/fastlane/fastlane/issues/1873. Please post all further comments there.

`fastlane` is now a mono repo, you can read more about the change in our [blog post](https://krausefx.com/blog/our-goal-to-unify-fastlane-tools). All tools are now available in the [fastlane main repo](https://github.com/fastlane/fastlane) :rocket:

**Closed by fastlane-bot-helper** 2016-03-07 19:55 UTC
Labels: bug, migrated
