### ISSUE TITLE
Submitting Changelog with Pilot didn't work

### ISSUE THREAD

**Issue by squarefrog** [fastlane/pilot#86] opened 2015-11-19 11:20 UTC
I've just submitted a new beta update using `pilot`, and I've noticed my change log string did not get submitted. I've not changed our `fastfile` since the last successful upload about a month ago, which did upload the change log.

I'm not sure if this is a one-time issue, or a regression due to iTunes Connect changes, but I'm leaving this issue open until I have another beta update to push out.

**Comment by squarefrog** [comment] 2015-11-19 11:33
Hmm.. I wonder if this is just an iTunes Connect issue. I went to manually add the 'What to test' information, and it wouldn't let me save after adding.

1. Log into iTunes Connect
2. Click on 'My Apps'
3. Click the App
4. Click the TestFlight tab
5. Click the iOS link under 'TESTFLIGHT BUILDS'
6. Click on the most recent build
7. Click 'Test Information'
8. Paste change log text into the 'What to Test' block
9. Save is still locked out, when it should be enabled

I'm an Admin so I should, and did formerly, have the privilege to update metadata.

**Comment by jorgeazevedo** [comment] 2015-11-19 16:02
I'm seeing the same behaviour. I tried to manually input "what to test", but the save button is disabled. I suspected this was because the account that uploaded the build wasn't the same I used to login. But I guess not?

**Comment by squarefrog** [comment] 2015-11-19 16:12
That is interesting. I did use the same account for it, however. I wonder if Apple have just disabled the ability to add notes for some reason?

**Comment by jorgeazevedo** [comment] 2015-11-19 16:28
I wonder if uploading it manually from the XCode GUI would give us the same behaviour? If it doesn't, then there might be something in what pilot is doing that's locking the whole "Test information" tab. Maybe something in iTC changed and it doesn't like pilot's payloads anymore.

**Comment by jorgeazevedo** [comment] 2015-11-20 10:20
Uploaded from XCode and the "Test information" is still unchangeable.
However, when the build is manually submitted for external beta in the iTC interface, it not only gives a chance to edit "what to test", it actually won't allow build to be submitted if the field is empty.

So I guess now it's only possible to fill in "what to test" during submission?

**Comment by squarefrog** [comment] 2015-11-20 10:22
Oh that is interesting. Thanks for testing that behaviour out :+1:

**Comment by micnguyen** [comment] 2015-12-15 04:00
I can confirm that through pilot the changelogs are not being sent properly to ITC. I have confirmed that the changelog strings are being built from the commits between HEAD and last tag, but when I look at my build - there is nothing in "What to Test".

However, I do have slightly different behaviour than @squarefrog @jorgeazevedo as I can manually add some text in the What to Test textbox by going to TestFlight > iOS Builds > Select the latest build > Test Information Tab and after entering some text, I can select the Save Button, so looks like Apple has fixed it on their front-end side, just not through the API.

**Comment by micnguyen** [comment] 2015-12-16 05:22
Just an update after some of my learnings:

You can indeed edit the "What to Test" field via ITC manually on the website, or even via SpaceShip (I just tested updated the whats_new parameter) and it does indeed save and reflect on the site. However, it appears the whats_new parameter is only show on the TestFlight app if you submit the whats_new data BEFORE it's been submitted for processing. ie: if you upload a build without a whats_new text, and it finishes processing, your users who have the TestFlight app WILL NOT see the text.

So there are two issues currently:
- pilot currently takes in changelog but not whats_new (which I thought was the same)
- pilot has to be sending the whats_new text as part of the submission upload for it to appear for users.

**Comment by ffittschen** [comment] 2016-01-08 16:27
I observed the same behaviour as described in https://github.com/fastlane/pilot/issues/86#issuecomment-164997974 but if have one addition: 

- If I add the "What to Test" text manually via ITC **during processing**, it shows up in the TestFlight app (even if I'm just testing internally)! So there is no need to submit the `whats_new` text BEFORE the app is submitted for processing.

A clarification between `whats_new` and `changelog` would be great. Looking at the source, it seems like the value of `changelog` is just assigned to `whats_new`. I think it would be more clear if the `Pilot` option is changed from `changelog` to `whats_new`.

Back to the topic:
The [`update_build_information`](https://github.com/fastlane/spaceship/blob/master/lib/spaceship/tunes/build.rb#L115) is only called during [`distribute_build`](https://github.com/fastlane/pilot/blob/master/lib/pilot/build_manager.rb#L102), but I think it should be called regardless of distributing the build to external testers. --> the call to `update_build_information` should be moved to [line 19](https://github.com/fastlane/pilot/blob/master/lib/pilot/build_manager.rb#L19), but this means we have to somehow work around `wait_for_processing_build` to get the latest build which is still processing

**Comment by ChristopherDrum** [comment] 2016-01-26 04:33
Just to put in my 2 cents on this. I agree with @ffittschen 's comments regarding the parameter names, as "changelog" has no obvious correlation to the TestFlight interface.

I'm curious to know how we can handle internalization of the changelog. Our app is localized in English and Japanese, and I would like to be able to give localized changelog strings for testers, though I see no parameters in Pilot that would allow for this.

Perhaps the "changelog" parameter could be underscore qualified as in "changelog_en-US", "changelog_ja-JP" (values would match Xcode app localization options, I think?)

**Comment by jacobvanorder** [comment] 2016-02-23 16:16
This is closed but I agree with @ffittschen, the change log should be submitted regardless of if it is submitted externally or internally.

**Comment by vpolouchkine** [comment] 2016-02-25 01:26
@jacobvanorder Could you create a separate issue and I'll mark it as a FR? It will be easier to track.

**Comment by jacobvanorder** [comment] 2016-02-25 15:30
@vpolouchkine Sure thing. It's not working either way but I'll give an overview of what would be nice to have.

**Comment by fastlane-bot-helper** [comment] 2016-03-07 19:59
This issue was migrated to https://github.com/fastlane/fastlane/issues/1894. Please post all further comments there.

`fastlane` is now a mono repo, you can read more about the change in our [blog post](https://krausefx.com/blog/our-goal-to-unify-fastlane-tools). All tools are now available in the [fastlane main repo](https://github.com/fastlane/fastlane) :rocket:

**Closed by fastlane-bot-helper** 2016-03-07 19:59 UTC
Labels: migrated
